# Generated by Django 5.0.7 on 2024-08-18 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='portion',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.IntegerField(default=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flan',
            name='flan_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
