# Generated by Django 5.0.7 on 2024-08-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_flan_ingredients_flan_stock_alter_flan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='price',
            field=models.IntegerField(default=2.49),
        ),
    ]
