# Generated by Django 5.0.7 on 2024-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='portion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flan',
            name='price',
            field=models.DecimalField(decimal_places=3, default=2.49, max_digits=10),
        ),
    ]
